import { useMemo, useState } from 'react';
import { Icon } from '../assets/icons.jsx';
import { contactFields, siteConfig } from '../config/siteConfig';

const initial = Object.fromEntries(contactFields.map((field) => [field.name, '']));
function validate(values) { const errors = {}; contactFields.forEach((field) => { if (field.required && !values[field.name].trim()) errors[field.name] = `${field.label} is required.`; }); if (values.email && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email)) errors.email = 'Enter a valid email address.'; if (values.phone && !/^[0-9+\-\s()]{7,}$/.test(values.phone)) errors.phone = 'Enter a valid phone number.'; return errors; }

export default function ApplicationForm() {
  const [values, setValues] = useState(initial); const [errors, setErrors] = useState({}); const [status, setStatus] = useState('idle'); const [notice, setNotice] = useState('');
  const submissionId = useMemo(() => `visioniim-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`, []);
  async function handleSubmit(event) { event.preventDefault(); if (status === 'submitting') return; const nextErrors = validate(values); setErrors(nextErrors); if (Object.keys(nextErrors).length) return; if (!siteConfig.formEndpoint) { setStatus('error'); setNotice('Form endpoint is not configured yet. Add VITE_GOOGLE_SCRIPT_URL to connect submissions.'); return; } setStatus('submitting'); setNotice(''); const body = new FormData(event.currentTarget); body.set('submissionId', submissionId); body.set('target', 'Contact form'); body.set('page', window.location.href); try { await fetch(siteConfig.formEndpoint, { method: 'POST', mode: 'no-cors', body }); setStatus('success'); setNotice('Thank you. Your message has been received.'); setValues(initial); } catch { setStatus('error'); setNotice('We could not submit the form. Please check your connection and try again.'); } }
  return <section className="section contact-section" id="contact"><div className="contact-photo photo photo-woman" role="img" aria-label="Missing Figma export: woman contact image"><span className="asset-note">Export from Figma<br/>woman contact image</span></div><form className="contact-card" onSubmit={handleSubmit} noValidate><h2>Get in touch</h2><p>Feel free to contact us with any questions or concerns. You can use the below form or email us directly.</p><input type="text" name="company" className="honeypot" tabIndex="-1" autoComplete="off" aria-hidden="true" />{contactFields.map((field)=><div className="contact-field" key={field.name}><label htmlFor={field.name}>{field.label}</label>{field.type==='textarea'?<textarea id={field.name} name={field.name} rows="4" placeholder={field.placeholder} value={values[field.name]} onChange={(e)=>setValues({...values,[field.name]:e.target.value})} aria-describedby={`${field.name}-error`} />:<input id={field.name} name={field.name} type={field.type} required={field.required} placeholder={field.placeholder} autoComplete={field.autoComplete} value={values[field.name]} onChange={(e)=>setValues({...values,[field.name]:e.target.value})} aria-describedby={`${field.name}-error`} />}{errors[field.name] && <p className="error" id={`${field.name}-error`}>{errors[field.name]}</p>}</div>)}<button className="btn btn-yellow submit" disabled={status==='submitting'}>{status==='submitting'?'Submitting…':'Submit'} <Icon name="arrow"/></button>{notice && <p className={`notice ${status}`} role="status">{notice}</p>}</form></section>;
}
